version: '3'

services:

  my_mongoDB:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=LaidsFruitsEtLegumes
      - MONGO_INITDB_ROOT_PASSWORD=LaidsFruitsEtLegumesPass
      # - MONGO_INITDB_DATABASE=LaidsFruitsEtLegumes
    ports:
      - 27018:27017
    volumes:
      - mongo-volume:/data/LaidsFruitsEtLegumes

volumes:
  mongo-volume:
